# Generated by Django 5.2.14 on 2026-06-12 13:53

import django.db.models.deletion
import django.utils.timezone
import pcba.designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_rename_client_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=50, verbose_name="SKU")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm.org"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hw_version", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="designs.design"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesignAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=pcba.designs.models.design_asset_upload_path
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            (
                                "Design Files",
                                [
                                    ("FUSION", "Fusion Electronics Project"),
                                    ("PCB_3D", "PCB 3D View"),
                                    ("PCB_TOP", "PCB Top View"),
                                    ("PCB_BOTTOM", "PCB Bottom View"),
                                    ("SCHEMATIC", "Schematic Design File"),
                                    ("PCB_DESIGN", "PCB Design File"),
                                    ("BOM", "Bill of Materials"),
                                    ("FIRMWARE", "Firmware Binary"),
                                ],
                            ),
                            ("Additional", [("ATTACHMENT", "Attachment")]),
                        ],
                        default="ATTACHMENT",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Do not show this asset to clients"
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="designs.designversion",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_type", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="designversion",
            constraint=models.UniqueConstraint(
                fields=("design", "hw_version"), name="unique_design_version"
            ),
        ),
    ]
