# Generated by Django 5.2.14 on 2026-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Used to highlight this operation in the UI",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
