# Generated by Django 5.2.14 on 2026-06-13 06:49

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    ProductionStage = apps.get_model("erp", "ProductionStage")
    for index, stage in enumerate(ProductionStage.objects.order_by("name"), start=1):
        stage.order = index
        stage.save(update_fields=["order"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_rename_to_production_stage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionstage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="productionstage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_initial_order, noop),
    ]
