# Generated by Django 5.2.14 on 2026-06-13 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0031_alter_design_client_delete_client"),
        ("erp", "0004_alter_productionstage_options_productionstage_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_dt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="device.design",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_dt"],
            },
        ),
        migrations.CreateModel(
            name="BatchOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("DONE", "Done"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="erp.batch",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
