# Generated by Django 5.2.14 on 2026-06-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_batch_batchoperation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BatchOperation",
            new_name="BatchProductionStage",
        ),
        migrations.AlterField(
            model_name="batchproductionstage",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_stages",
                to="erp.batch",
            ),
        ),
    ]
