# Generated by Django 5.2.14 on 2026-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_rename_batchoperation_to_batchproductionstage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchproductionstage",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
