# Generated by Django 5.0.2 on 2026-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_alter_batchproductionstage_completion_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionstagetemplate",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="productionstagetemplate",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
