# Generated by Django 5.0.2 on 2026-06-16 08:20

import django.db.models.deletion
import django.utils.timezone
import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_add_part_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="Component device or part identifier",
                        max_length=200,
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        blank=True,
                        help_text="Package type (e.g. 0402, SOT-23)",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Component value (e.g. 10k, 100nF)",
                        max_length=100,
                    ),
                ),
                (
                    "fusion_library",
                    models.CharField(
                        blank=True,
                        help_text="Fusion Electronics library name",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="part_images/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_dt", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=erp.models.part_asset_upload_path)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
