# Generated by Django 5.0.2 on 2026-06-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_add_part_and_part_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to="erp.partcategory",
            ),
        ),
    ]
