# Generated by Django 5.2.14 on 2026-06-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0012_add_category_to_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="notes",
        ),
    ]
