# Generated by Django 5.2.14 on 2026-06-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_remove_part_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_sku", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
                ("manufacturer_sku", models.CharField(blank=True, max_length=200)),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank if stock level is unknown",
                        null=True,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["supplier_name"],
            },
        ),
    ]
