# Generated by Django 5.0.2 on 2026-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0014_add_part_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsource",
            name="packaging",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
