# Generated by Django 5.0.2 on 2026-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0015_add_partsource_packaging"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomEquivalenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any library",
                        max_length=200,
                    ),
                ),
                (
                    "from_device",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any device",
                        max_length=200,
                    ),
                ),
                (
                    "from_value",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any value",
                        max_length=100,
                    ),
                ),
                (
                    "to_device",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to leave the device unchanged",
                        max_length=200,
                    ),
                ),
                (
                    "to_value",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to leave the value unchanged",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["library", "from_device", "from_value"],
            },
        ),
        migrations.CreateModel(
            name="BomExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any library",
                        max_length=200,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any device",
                        max_length=200,
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any package",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["library", "device", "package"],
            },
        ),
        migrations.CreateModel(
            name="BomLibrarySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library",
                    models.CharField(
                        help_text="Fusion Electronics library name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "ignore_value",
                    models.BooleanField(
                        default=False,
                        help_text="When importing parts from this library, ignore the 'value' field: it is not used to detect duplicates and is not stored on the part.",
                    ),
                ),
            ],
            options={
                "ordering": ["library"],
            },
        ),
    ]
