# Generated by Django 5.0.2 on 2026-06-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0016_bomequivalencerule_bomexclusionrule_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bomexclusionrule",
            options={"ordering": ["library", "device", "package", "value"]},
        ),
        migrations.AddField(
            model_name="bomexclusionrule",
            name="value",
            field=models.CharField(
                blank=True, help_text="Leave blank to match any value", max_length=100
            ),
        ),
    ]
