# Generated by Django 5.0.2 on 2026-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0017_alter_bomexclusionrule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomlibrarysetting",
            name="ignore_device",
            field=models.BooleanField(
                default=False,
                help_text="When importing parts from this library, ignore the 'device' field: it is not used to detect duplicates and is not stored on the part.",
            ),
        ),
        migrations.AddField(
            model_name="bomlibrarysetting",
            name="ignore_package",
            field=models.BooleanField(
                default=False,
                help_text="When importing parts from this library, ignore the 'package' field: it is not used to detect duplicates and is not stored on the part.",
            ),
        ),
    ]
