# Generated by Django 5.0.2 on 2026-06-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0018_bomlibrarysetting_ignore_device_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bomequivalencerule",
            options={
                "ordering": ["library", "from_device", "from_package", "from_value"]
            },
        ),
        migrations.AddField(
            model_name="bomequivalencerule",
            name="from_package",
            field=models.CharField(
                blank=True, help_text="Leave blank to match any package", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="bomequivalencerule",
            name="to_package",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to leave the package unchanged",
                max_length=100,
            ),
        ),
    ]
