# Generated by Django 5.2.14 on 2026-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0019_alter_bomequivalencerule_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bomequivalencerule",
            options={
                "ordering": [
                    "from_library",
                    "from_device",
                    "from_package",
                    "from_value",
                ]
            },
        ),
        migrations.RenameField(
            model_name="bomequivalencerule",
            old_name="library",
            new_name="from_library",
        ),
        migrations.AddField(
            model_name="bomequivalencerule",
            name="to_library",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to leave the library unchanged",
                max_length=200,
            ),
        ),
    ]
