# Generated by Django 5.2.14 on 2026-06-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0020_alter_bomequivalencerule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="erp.part",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_for",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["substitute__name"],
                "unique_together": {("part", "substitute")},
            },
        ),
    ]
