# Generated by Django 5.2.14 on 2026-06-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0021_part_substitution"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartPriceBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_breaks",
                        to="erp.partsource",
                    ),
                ),
            ],
            options={
                "ordering": ["quantity"],
                "unique_together": {("source", "quantity")},
            },
        ),
    ]
