# Generated by Django 5.2.14 on 2026-06-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0027_merge_duplicate_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsourcevariant",
            name="moq",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum order quantity; leave blank if unknown",
                null=True,
            ),
        ),
    ]
