# Generated by Django 5.2.14 on 2026-06-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0028_add_variant_moq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="reference",
            new_name="po",
        ),
        migrations.AlterField(
            model_name="batch",
            name="po",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Purchase order"
            ),
        ),
    ]
