# Generated by Django 5.2.14 on 2026-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0029_remove_batch_reference_batch_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsourcevariant",
            name="last_refreshed",
            field=models.DateTimeField(
                blank=True,
                help_text="When pricing/stock was last fetched from the supplier API",
                null=True,
            ),
        ),
    ]
