# Generated by Django 5.2.14 on 2026-06-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0033_design_obsolete"),
        ("erp", "0030_partsourcevariant_last_refreshed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignBomEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Reference designator (e.g. R3)", max_length=50
                    ),
                ),
                (
                    "pos_x",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "pos_y",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "rotation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("TOP", "Top"), ("BOTTOM", "Bottom")],
                        max_length=6,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_entries",
                        to="device.design",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_bom_entries",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["reference"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("design", "reference"),
                        name="unique_design_bom_reference",
                    )
                ],
            },
        ),
    ]
