# Generated by Django 5.2.14 on 2026-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0031_designbomentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="stock",
            field=models.IntegerField(
                blank=True,
                help_text="Manually-tracked on-hand stock count, independent of supplier listings",
                null=True,
            ),
        ),
    ]
