# Generated by Django 5.0.2 on 2026-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0032_part_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="no_stock_required",
            field=models.BooleanField(
                default=False,
                help_text="Part is placed on the BOM but never physically stocked (e.g. test points, DNP parts)",
            ),
        ),
    ]
