# Generated by Django 5.0.2 on 2026-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0033_part_no_stock_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="pth_joints",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of PTH (through-hole) solder joints for one placement of this part",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="smt_joints",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of SMT solder joints for one placement of this part",
                null=True,
            ),
        ),
    ]
