# Generated by Django 5.0.2 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0034_part_pth_joints_part_smt_joints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="smt_joints",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of SMT (surface-mount) solder joints for one placement of this part",
                null=True,
            ),
        ),
    ]
