# Generated by Django 5.0.2 on 2026-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0035_alter_part_smt_joints"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyCostSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smt_joint_cost_cents",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="e.g. 0.5 for half a cent",
                        max_digits=8,
                        verbose_name="Cost per SMT joint (cents)",
                    ),
                ),
                (
                    "pth_joint_cost_cents",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="e.g. 5 for five cents",
                        max_digits=8,
                        verbose_name="Cost per PTH joint (cents)",
                    ),
                ),
                (
                    "labour_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Charge per hour of assembly labour",
                        max_digits=10,
                        verbose_name="Assembly labour rate",
                    ),
                ),
                (
                    "kitting_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="e.g. 20 for 20%",
                        max_digits=6,
                        verbose_name="Parts kitting margin (%)",
                    ),
                ),
                (
                    "conformal_coating_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "anti_shock_glue_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Assembly cost settings",
                "verbose_name_plural": "Assembly cost settings",
            },
        ),
    ]
