# Generated by Django 5.0.2 on 2026-07-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0036_assemblycostsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartSourceStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(blank=True, null=True)),
                ("recorded_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="erp.partsource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "part source stock history",
                "ordering": ["-recorded_dt"],
            },
        ),
    ]
