# Generated by Django 5.0.2 on 2026-07-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0037_partsourcestockhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartPriceBreakHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("recorded_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_break_history",
                        to="erp.partsourcevariant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "part price break history",
                "ordering": ["-recorded_dt", "quantity"],
            },
        ),
    ]
