# Generated by Django 5.0.2 on 2026-07-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0038_partpricebreakhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomSupplementRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any library",
                        max_length=200,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any device",
                        max_length=200,
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any package",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any value",
                        max_length=100,
                    ),
                ),
                (
                    "supplement_library",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to copy the matched row's library. Give it a distinct name if the matched library has an Ignore Value library setting, or that setting will blank this row's Value too.",
                        max_length=200,
                    ),
                ),
                (
                    "supplement_device",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to copy the matched row's device",
                        max_length=200,
                    ),
                ),
                (
                    "supplement_package",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to copy the matched row's package",
                        max_length=100,
                    ),
                ),
                (
                    "supplement_value",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to copy the matched row's value",
                        max_length=100,
                    ),
                ),
                (
                    "reference_suffix",
                    models.CharField(
                        help_text='Appended to the matched row\'s reference designator to make a unique reference for the generated entry, e.g. "-FUSE" turns F1 into F1-FUSE.',
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["library", "device", "package", "value"],
            },
        ),
    ]
