# Generated by Django 5.2.16 on 2026-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0040_backfill_partsourcestockhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="committed_stock",
            field=models.IntegerField(
                blank=True,
                help_text="Manually-tracked stock already allocated to a build",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="incoming_stock",
            field=models.IntegerField(
                blank=True,
                help_text="Manually-tracked stock on order but not yet received",
                null=True,
            ),
        ),
    ]
