# Generated by Django 5.2.16 on 2026-07-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0041_part_committed_stock_part_incoming_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_order_number", models.CharField(max_length=200)),
                (
                    "order_dt",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was placed, per the supplier",
                        null=True,
                    ),
                ),
                (
                    "expected_arrival_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if unknown/not reported",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Raw status string as reported by the supplier",
                        max_length=100,
                    ),
                ),
                ("last_refreshed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-order_dt"],
                "unique_together": {("supplier_name", "supplier_order_number")},
            },
        ),
        migrations.CreateModel(
            name="PartsOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True,
                        help_text="Raw supplier SKU as ordered, kept even if matching fails or the listing is later deleted",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SHIPPED", "Shipped"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts_order_lines",
                        to="erp.part",
                    ),
                ),
                (
                    "part_source_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts_order_lines",
                        to="erp.partsourcevariant",
                    ),
                ),
                (
                    "parts_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="erp.partsorder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
