# Generated by Django 5.0.2 on 2026-07-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0042_partsorder_partsorderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsorder",
            name="supplier_order_url",
            field=models.URLField(
                blank=True,
                help_text="Link to this order on the supplier's own website, if known. Populated at sync time (see erp.views._digikey_order_url) rather than computed on read, since it needs a field DigiKey's own docs don't flag as the important one: the website's OrderHistory/ReviewOrder page keys off OrderNumber, not the Sales Order ID that supplier_order_number stores (confirmed by comparing a real order - DigiKey's order LIST page and API both surface \"Sales Order ID\" as the order's number, but the review PAGE URL uses the separate, longer OrderNumber value instead).",
            ),
        ),
    ]
