# Generated by Django 5.0.2 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0043_partsorder_supplier_order_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsorderline",
            name="received",
            field=models.BooleanField(
                default=False,
                help_text="Manually confirmed as physically received into stock (not from the supplier feed)",
            ),
        ),
        migrations.AddField(
            model_name="partsorderline",
            name="received_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partsorderline",
            name="supplier_line_number",
            field=models.CharField(
                blank=True,
                help_text="Supplier's own per-line identifier within the order (DigiKey's DetailId), used to match this line across resyncs so received survives a refresh",
                max_length=50,
            ),
        ),
    ]
