# Generated by Django 5.0.2 on 2026-07-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0044_partsorderline_received_partsorderline_received_dt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="incoming_stock",
        ),
    ]
