# Generated by Django 5.2.16 on 2026-07-27 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0045_remove_part_incoming_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsCartLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text='e.g. "R&D", "general stock"', null=True
                    ),
                ),
                (
                    "ordered",
                    models.BooleanField(
                        default=False,
                        help_text="Manually marked as ordered - purely local bookkeeping, not linked to any PartsOrder",
                    ),
                ),
                ("ordered_dt", models.DateTimeField(blank=True, null=True)),
                ("added_dt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The batch this quantity is required for, if any; blank for manual R&D/stock adds",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_lines",
                        to="erp.batch",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_lines",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_dt"],
            },
        ),
    ]
