# Generated by Django 5.2.16 on 2026-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0046_partscartline"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
