# Generated by Django 5.2.17 on 2026-08-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0047_batch_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("recorded_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="erp.part",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "part stock history",
                "ordering": ["-recorded_dt"],
            },
        ),
    ]
