# Generated by Django 5.2.16 on 2026-08-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0037_remove_design_pcb_part_design_pcb_stock"),
        ("erp", "0049_backfill_partstockhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsorderline",
            name="design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pcb_order_lines",
                to="device.design",
            ),
        ),
        migrations.CreateModel(
            name="DesignPcbStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("recorded_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcb_stock_history",
                        to="device.design",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "design pcb stock history",
                "ordering": ["-recorded_dt"],
            },
        ),
    ]
