# Generated by Django 5.0.2 on 2024-06-17 06:20

from django.db import migrations


def add_site_entry(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    if Site.objects.filter(pk=1).exists():
        return
    Site.objects.create(pk=1, domain='portal.superhouse.tv', name='SuperHouse')


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_rename_name_user_full_name_user_preferred_name"),
    ]

    operations = []
