# Generated by Django 5.2.14 on 2026-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0004_user_avatar_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
