# Generated by Django 5.2.14 on 2026-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_manufacturer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="is_supplier",
            field=models.BooleanField(default=False),
        ),
    ]
