# Generated by Django 5.2.14 on 2026-06-08 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_client_is_client_client_is_manufacturer_and_more"),
        ("device", "0031_alter_design_client_delete_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Org",
        ),
    ]
