# Generated by Django 5.2.14 on 2026-06-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_copy_org_api_keys_to_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="api_key",
        ),
    ]
