# Generated by Django 5.0.2 on 2026-07-06 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0033_design_obsolete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestModuleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(blank=True, max_length=20)),
                (
                    "compatible_designs",
                    models.ManyToManyField(
                        blank=True, related_name="test_module_types", to="device.design"
                    ),
                ),
            ],
            options={
                "ordering": ["name", "version"],
            },
        ),
        migrations.CreateModel(
            name="TestModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "module_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="testing.testmoduletype",
                    ),
                ),
            ],
            options={
                "ordering": ["module_type__name", "module_type__version", "pk"],
            },
        ),
    ]
