# Generated by Django 5.2.17 on 2026-08-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0037_remove_design_pcb_part_design_pcb_stock"),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suites",
                        to="device.design",
                    ),
                ),
            ],
            options={
                "ordering": ["design", "-version"],
            },
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("DELAY", "Delay"),
                            ("UPLOAD_FIRMWARE", "Upload Firmware"),
                            ("BEEP", "Beep"),
                            ("READ_RAIL_VOLTAGE", "Read Rail Voltage"),
                            ("READ_RAIL_CURRENT", "Read Rail Current"),
                            ("CONTROL_POWER_RAIL", "Control Power Rail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hard_fail", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="testing.testsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="testsuite",
            constraint=models.UniqueConstraint(
                fields=("design", "version"), name="unique_design_test_suite_version"
            ),
        ),
    ]
