# Generated by Django 5.2.16 on 2026-08-26 02:04
from django.db import migrations, models
from django.db.models import Max


def mark_current_suites_as_draft(apps, schema_editor):
    """Backfill for issue #110: every existing TestSuite defaults to SAVED (immutable) via the
    AddField above, but under the pre-fix behaviour each design's highest-version row was always
    freely editable in place - the closest existing equivalent to a draft. Flip just that one row
    per design to DRAFT so existing designs keep behaving the same way (still directly editable)
    immediately after this migration, rather than requiring an edit to fork a new version first."""
    TestSuite = apps.get_model('testing', 'TestSuite')
    highest_per_design = TestSuite.objects.values('design_id').annotate(max_version=Max('version'))
    for row in highest_per_design:
        TestSuite.objects.filter(design_id=row['design_id'], version=row['max_version']).update(status='DRAFT')


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0003_alter_teststep_step_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuite",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SAVED", "Saved")],
                default="SAVED",
                max_length=10,
            ),
        ),
        migrations.RunPython(mark_current_suites_as_draft, migrations.RunPython.noop),
    ]
