# Generated by Django 5.2.16 on 2026-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0004_testsuite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teststep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("DELAY", "Delay"),
                    ("UPLOAD_FIRMWARE", "Upload Firmware"),
                    ("BEEP", "Beep"),
                    ("READ_RAIL_VOLTAGE", "Read Rail Voltage"),
                    ("READ_RAIL_CURRENT", "Read Rail Current"),
                    ("CONTROL_POWER_RAIL", "Control Power Rail"),
                    ("PYTHON", "Python"),
                    ("IOMOD_ANALOG_READ", "IOMOD Analog Read"),
                    ("IOMOD_DIGITAL_READ", "IOMOD Digital Read"),
                    ("IOMOD_DIGITAL_WRITE", "IOMOD Digital Write"),
                    ("IOMOD_ANALOG_WRITE", "IOMOD Analog Write"),
                    ("LED_SPECTRAL_READING", "LED Spectral Reading"),
                ],
                max_length=32,
            ),
        ),
    ]
