# Generated by Django 5.2.16 on 2026-08-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0006_alter_teststep_step_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.CharField(max_length=255)),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_checks",
                        to="testing.testsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
