# Generated by Django 5.2.17 on 2026-08-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0007_manualcheck"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teststep",
            old_name="hard_fail",
            new_name="abort_on_fail",
        ),
    ]
