# Generated by Django 5.2.17 on 2026-09-06 11:05
#
# Issue #121: splits the single UPLOAD_FIRMWARE Test Step type into 4 tool-specific types
# (avrdude / esptool.py / OpenOCD / STM32CubeProgrammer), each with its own config fields.
# The data migration below converts any existing UPLOAD_FIRMWARE rows before the choices
# list changes, so a saved/frozen Test Suite version keeps rendering (colour, config
# summary) correctly instead of silently falling back to an unrecognised step_type.

from django.db import migrations, models

# Maps the old config['upload_tool'] value to its new dedicated step_type. Unrecognised or
# missing values fall back to avrdude - an arbitrary but harmless choice, since a step in
# this state was already missing its required config and needed editing regardless.
UPLOAD_TOOL_TO_STEP_TYPE = {
    "avrdude": "UPLOAD_FIRMWARE_AVRDUDE",
    "esptool.py": "UPLOAD_FIRMWARE_ESPTOOL",
    "openocd": "UPLOAD_FIRMWARE_OPENOCD",
    "stm32cubeprogrammer": "UPLOAD_FIRMWARE_STM32CUBEPROGRAMMER",
}
STEP_TYPE_TO_UPLOAD_TOOL = {v: k for k, v in UPLOAD_TOOL_TO_STEP_TYPE.items()}


def split_upload_firmware_forwards(apps, schema_editor):
    TestStep = apps.get_model("testing", "TestStep")
    for step in TestStep.objects.filter(step_type="UPLOAD_FIRMWARE"):
        config = dict(step.config or {})
        new_type = UPLOAD_TOOL_TO_STEP_TYPE.get(config.pop("upload_tool", None), "UPLOAD_FIRMWARE_AVRDUDE")
        step.step_type = new_type
        step.config = config
        step.save(update_fields=["step_type", "config"])


def split_upload_firmware_backwards(apps, schema_editor):
    # Best-effort/lossy: reconstructs upload_tool from the new step_type, but tool-specific
    # fields that didn't exist on the old UPLOAD_FIRMWARE shape (programmer_type, mcu, chip,
    # images, interface_config, target_config, adapter_serial, connection_interface,
    # flash_address, baud_rate) are left in config as-is rather than discarded, since there's
    # no old field to map them back to.
    TestStep = apps.get_model("testing", "TestStep")
    for step in TestStep.objects.filter(step_type__in=STEP_TYPE_TO_UPLOAD_TOOL):
        config = dict(step.config or {})
        config["upload_tool"] = STEP_TYPE_TO_UPLOAD_TOOL[step.step_type]
        step.step_type = "UPLOAD_FIRMWARE"
        step.config = config
        step.save(update_fields=["step_type", "config"])


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0008_rename_hard_fail_to_abort_on_fail"),
    ]

    operations = [
        migrations.RunPython(split_upload_firmware_forwards, split_upload_firmware_backwards),
        migrations.AlterField(
            model_name="teststep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("DELAY", "Delay"),
                    ("UPLOAD_FIRMWARE_AVRDUDE", "Upload Firmware (avrdude)"),
                    ("UPLOAD_FIRMWARE_ESPTOOL", "Upload Firmware (esptool.py)"),
                    ("UPLOAD_FIRMWARE_OPENOCD", "Upload Firmware (OpenOCD)"),
                    (
                        "UPLOAD_FIRMWARE_STM32CUBEPROGRAMMER",
                        "Upload Firmware (STM32CubeProgrammer)",
                    ),
                    ("BEEP", "Beep"),
                    ("READ_RAIL_VOLTAGE", "Read Rail Voltage"),
                    ("READ_RAIL_CURRENT", "Read Rail Current"),
                    ("CONTROL_POWER_RAIL", "Control Power Rail"),
                    ("PYTHON", "Python"),
                    ("IOMOD_ANALOG_READ", "IOMOD Analog Read"),
                    ("IOMOD_DIGITAL_READ", "IOMOD Digital Read"),
                    ("IOMOD_DIGITAL_WRITE", "IOMOD Digital Write"),
                    ("IOMOD_ANALOG_WRITE", "IOMOD Analog Write"),
                    ("LED_SPECTRAL_READING", "LED Spectral Reading"),
                    ("OPERATOR_INTERVENTION", "Operator Intervention"),
                ],
                max_length=40,
            ),
        ),
    ]
