# Generated by Django 5.2.17 on 2026-09-06 12:26

import django.db.models.deletion
import django.utils.timezone
import testing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0009_split_upload_firmware_test_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestStepAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=testing.models.test_step_asset_upload_path
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=32)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="testing.teststep",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
    ]
