# Generated by Django 5.2.17 on 2026-09-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0010_teststepasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststep",
            name="include_on_docket",
            field=models.BooleanField(default=True),
        ),
    ]
