# Generated by Django 5.2.17 on 2026-09-22 00:14

import django.db.models.deletion
import django.utils.timezone
import testing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0011_teststep_include_on_docket"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststep",
            name="diagnostic_note",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="TestStepDiagnosticImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=testing.models.test_step_diagnostic_image_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_images",
                        to="testing.teststep",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
    ]
