# Generated by Django 5.2.17 on 2026-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0012_teststep_diagnostic_note_teststepdiagnosticimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tester",
            name="api_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
