# Generated by Django 5.0.2 on 2024-04-24 06:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.design')),
            ],
        ),
    ]
