# Generated by Django 5.0.2 on 2024-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_client_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="version",
            new_name="hw_version",
        ),
        migrations.AddField(
            model_name="device",
            name="sw_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
