# Generated by Django 5.0.2 on 2024-05-12 01:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_rename_version_design_hw_version_device_sw_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_dt", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("NEW", "STARTED"),
                            ("PASS", "PASSED"),
                            ("FAIL", "FAILED"),
                            ("HUH?", "INCONCLUSIVE"),
                        ],
                        default="NEW",
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.device"
                    ),
                ),
            ],
        ),
    ]
