# Generated by Django 5.0.2 on 2024-05-12 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_testrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "test_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.testrecord",
                    ),
                ),
            ],
        ),
    ]
