# Generated by Django 5.0.2 on 2024-05-24 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_testimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="assembly_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="testrecord",
            name="test_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
