# Generated by Django 5.0.2 on 2024-05-26 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_alter_device_assembly_date_alter_testrecord_test_dt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_dt",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="When"
                    ),
                ),
                ("event_type", models.CharField(default="NOTE", max_length=50)),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Do not show this event to clients"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.device"
                    ),
                ),
            ],
            options={
                "ordering": ["event_dt"],
            },
        ),
    ]
