# Generated by Django 5.0.2 on 2024-05-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0009_deviceevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testrecord",
            options={"ordering": ["test_dt"]},
        ),
    ]
