# Generated by Django 5.0.2 on 2024-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0011_alter_testrecord_result"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="design",
            constraint=models.UniqueConstraint(
                fields=("sku", "hw_version"), name="unique_sku_hwversion"
            ),
        ),
    ]
