# Generated by Django 5.0.2 on 2024-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0012_design_unique_sku_hwversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="price2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
