# Generated by Django 5.0.2 on 2024-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0013_design_price_design_price2"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="invoice",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
