# Generated by Django 5.0.2 on 2024-06-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0014_device_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deviceevent",
            options={"ordering": ["device__id", "event_dt"]},
        ),
    ]
