# Generated by Django 5.0.2 on 2024-06-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0015_alter_deviceevent_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceevent",
            name="event_type",
        ),
        migrations.AddField(
            model_name="device",
            name="shipping",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
