# Generated by Django 5.0.2 on 2024-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0016_remove_deviceevent_event_type_device_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="shipping",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
