# Generated by Django 5.0.2 on 2024-07-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0017_alter_device_shipping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="assembly_date",
            new_name="creation_date",
        ),
    ]
