# Generated by Django 5.0.2 on 2024-07-25 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0018_rename_assembly_date_device_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="creation_date",
            new_name="creation_dt",
        ),
        migrations.AlterField(
            model_name="device",
            name="creation_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
