# Generated by Django 5.0.2 on 2024-07-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0019_alter_device_creation_date_to_creation_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("NOTE", "NOTE"),
                    ("SW_VERSION", "SW_VERSION"),
                    ("SHIPPING", "SHIPPING"),
                ],
                default="NOTE",
                max_length=50,
            ),
        ),
    ]
