# Generated by Django 5.0.2 on 2024-07-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0020_deviceevent_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="shipping",
        ),
        migrations.RemoveField(
            model_name="device",
            name="sw_version",
        ),
    ]
