# Generated by Django 5.0.2 on 2024-07-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0021_remove_device_shipping_remove_device_sw_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="po",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Purchase order"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clients/"),
        ),
        migrations.AlterField(
            model_name="testimage",
            name="image",
            field=models.ImageField(upload_to="test_images/"),
        ),
    ]
