# Generated by Django 5.0.2 on 2024-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0022_device_po_alter_client_logo_alter_testimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="api_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
