# Generated by Django 5.0.2

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0023_client_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_dt",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="When"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="device_images/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device__id", "-image_dt"],
            },
        ),
    ]

