# Generated by Django 5.0.2 on 2026-05-25 10:28

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0024_deviceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceimage",
            name="image",
            field=models.ImageField(upload_to=device.models.device_image_upload_path),
        ),
    ]
