# Generated by Django 5.0.2 on 2026-06-02 01:59

import device.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0025_alter_deviceimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=device.models.design_asset_upload_path),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("SCHEMATIC", "Schematic"),
                            ("GERBER", "Gerber"),
                            ("BOM", "Bill of Materials"),
                            ("FIRMWARE", "Firmware"),
                            ("DATASHEET", "Datasheet"),
                            ("IMAGE", "Image"),
                            ("DOC", "Document"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Do not show this asset to clients"
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.design"
                    ),
                ),
            ],
            options={
                "ordering": ["asset_type", "name"],
            },
        ),
    ]
