# Generated by Django 5.0.2 on 2026-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0026_designasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("FUSION", "Fusion Electronics Project"),
                    ("BOM", "Bill of Materials"),
                    ("FIRMWARE", "Firmware Binary"),
                    ("IMAGE", "Image"),
                    ("DOC", "Document"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
