# Generated by Django 5.0.2 on 2026-06-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0027_designasset_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("FUSION", "Fusion Electronics Project"),
                    ("PCB_DESIGN", "PCB Design File"),
                    ("SCHEMATIC", "Schematic Design File"),
                    ("BOM", "Bill of Materials"),
                    ("PCB_TOP", "PCB Top Preview"),
                    ("PCB_BOTTOM", "PCB Bottom Preview"),
                    ("PCB_3D", "PCB 3D Preview"),
                    ("FIRMWARE", "Firmware Binary"),
                    ("IMAGE", "Image"),
                    ("DOC", "PDF Document"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
