# Generated by Django 5.0.2 on 2026-06-03 10:25

import device.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0029_designasset_core_and_attachment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    (
                        "Design Files",
                        [
                            ("FUSION", "Fusion Electronics Project"),
                            ("PCB_3D", "PCB 3D View"),
                            ("PCB_TOP", "PCB Top View"),
                            ("PCB_BOTTOM", "PCB Bottom View"),
                            ("SCHEMATIC", "Schematic Design File"),
                            ("PCB_DESIGN", "PCB Design File"),
                            ("BOM", "Bill of Materials"),
                            ("FIRMWARE", "Firmware Binary"),
                        ],
                    ),
                    ("Additional", [("ATTACHMENT", "Attachment")]),
                ],
                default="ATTACHMENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeviceAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=device.models.device_asset_upload_path),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("ATTACHMENT", "Attachment")],
                        default="ATTACHMENT",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_dt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="Do not show this asset to clients"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.device"
                    ),
                ),
            ],
            options={
                "ordering": ["asset_type", "name"],
            },
        ),
    ]
