# Generated by Django 5.2.14 on 2026-06-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_copy_clients_from_device"),
        ("device", "0030_add_device_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.client"
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
