# Generated by Django 5.2.14 on 2026-06-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_rename_client_org"),
        ("device", "0031_alter_design_client_delete_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_client",
                to="crm.org",
            ),
        ),
    ]
