# Generated by Django 5.2.14 on 2026-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0032_alter_design_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="obsolete",
            field=models.BooleanField(default=False),
        ),
    ]
