# Generated by Django 5.0.2 on 2026-07-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0033_design_obsolete"),
        ("erp", "0035_alter_part_smt_joints"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="erp.batch",
            ),
        ),
    ]
