# Generated by Django 5.0.2 on 2026-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0034_device_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="additional_materials",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Additional Materials",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="anti_shock_glue",
            field=models.BooleanField(default=False, verbose_name="Anti-Shock Glue"),
        ),
        migrations.AddField(
            model_name="design",
            name="assembly_time_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Minutes", verbose_name="Assembly Time"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="conformal_coating",
            field=models.BooleanField(default=False, verbose_name="Conformal Coating"),
        ),
        migrations.AddField(
            model_name="design",
            name="packaging",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Packaging"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="pcb_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="PCB Cost"
            ),
        ),
    ]
