# Generated by Django 5.2.17 on 2026-08-11 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0035_design_additional_materials_design_anti_shock_glue_and_more"),
        ("erp", "0049_backfill_partstockhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="pcb_part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designs",
                to="erp.part",
                verbose_name="PCB Part",
            ),
        ),
    ]
