# Generated by Django 5.2.16 on 2026-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0036_design_pcb_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="design",
            name="pcb_part",
        ),
        migrations.AddField(
            model_name="design",
            name="pcb_stock",
            field=models.IntegerField(
                blank=True,
                help_text="Manually-tracked PCB stock count; also updated when a JLCPCB order line is marked received",
                null=True,
                verbose_name="PCB Stock",
            ),
        ),
    ]
