# Generated by Django 5.2.17 on 2026-09-28 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0037_remove_design_pcb_part_design_pcb_stock"),
        ("testing", "0013_tester_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceevent",
            name="created_by_tester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="testing.tester",
            ),
        ),
        migrations.AddField(
            model_name="deviceevent",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("created_by_tester__isnull", False),
                    ("created_by_user__isnull", False),
                    _negated=True,
                ),
                name="device_deviceevent_single_creator",
            ),
        ),
    ]
