"""
Django project settings.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys

from pathlib import Path

from django.contrib.messages import constants as messages

from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get("SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    # Apps in the venv
    'hijack',
    'hijack.contrib.admin',
    # See end of this file for debug tools
    'easy_thumbnails',
    # Apps in this project
    'authuser',
    'device',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'login_required.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'hijack.middleware.HijackUserMiddleware',
    'conf.middleware.TimezoneMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'device.context_processor.background_processor',  # Variables for customising the background
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Moved to local_settings.py

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'authuser.User'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/device/'
LOGOUT_REDIRECT_URL = '/device/'

LOGIN_REQUIRED_IGNORE_PATHS = [
    '/office/login/',
    '/office/logout/',
    '/admin/',
    '/static/',
    '__debug__/',
]

LOGIN_REQUIRED_IGNORE_VIEW_NAMES = [
    'login',
    'logout',
    'password_reset',
    'password_reset_done',
    'password_reset_confirm',
    'password_reset_complete',
]

HIJACK_PERMISSION_CHECK = 'hijack.permissions.superusers_and_staff'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-AU'

TIME_ZONE = 'Australia/Melbourne'
USE_TZ = True

USE_I18N = False
USE_L10N = False

DATE_FORMAT = 'j-N-Y'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    # "/var/www/static/",
]

MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": "DEBUG",
#     },
#     'loggers': {
#         'django.request': {
#             'handlers': ['console'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }

THUMBNAIL_BASEDIR = 'thumbs'
THUMBNAIL_DEBUG = True
THUMBNAIL_ALIASES = {
    '': {
        'vsmall': {
            'size': (32, 32),
        },
        'testimage-admin-thumbs': {
            'size': (130, 130),
        },
        'testimage-thumbs': {
            'size': (270, 270),
        },
    },
}

DEPLOY_TYPE = os.environ.get("DEPLOY_TYPE")
BACKGROUND_SETTINGS = {
    'dev': {
        'CSS_BODY_BACKGROUND_COLOUR': '#e5edf5',
        'CSS_BODY_BACKGROUND_IMAGE': None,
        # 'CSS_MAINWRAPPER_BACKGROUND_COLOUR': '#ffffff',
    },
    'test': {
        'CSS_BODY_BACKGROUND_COLOUR': '#fff6f6',
        'CSS_BODY_BACKGROUND_IMAGE': '/static/img/test-server-en.png',
        # 'CSS_MAINWRAPPER_BACKGROUND_COLOUR': 'transparent',
    },
    'prod': {
        'CSS_BODY_BACKGROUND_COLOUR': None,
        # 'CSS_BODY_BACKGROUND_IMAGE': '/static/img/live-data-dont-use-en.png',
        'CSS_BODY_BACKGROUND_IMAGE': None,
        # 'CSS_MAINWRAPPER_BACKGROUND_COLOUR': 'transparent',
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_TLS = True
EMAIL_SSL = False

try:
    from .local_settings import *
except ImportError:
    print('Unable to load local_settings.py')

TESTING = any(word in sys.argv for word in ('test', 'pytest'))

if DEBUG:
    if TESTING:
        # EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
        pass
    else:
        INSTALLED_APPS.append('debug_toolbar')
        INSTALLED_APPS.append('django_extensions')
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
